---
language: java
jdk: openjdk8
after_success:
  - './gradlew run --args=docs/index.html'
  - 'cat docs/index.html'
  - 'ls -l docs'
deploy:
    provider: bintray
    file: build/bintray.json
    user: $BINTRAY_USERNAME
    key: $BINTRAY_API_KEY
    skip_cleanup: true
    on:
        tags: true
