---
language: java
jdk: openjdk8
after_success:
  - './gradlew run --args=docs/index.html'
  - 'cat docs/index.html'
  - 'ls -l docs'
  - 'git remote -v show'
  - 'git checkout master'
  - 'git add docs'
  - 'git commit -m "commit build artifacts"'
  - 'git status'
  - 'git remote add origin2 https://cmosher01:$GITHUB_TOKEN@github.com/cmosher01/Solarized-Study.git'
  - 'git push origin2 master'
  - 'ls -al ~/'
  - 'ls -al ~/.ssh'
deploy:
    provider: bintray
    file: build/bintray.json
    user: $BINTRAY_USERNAME
    key: $BINTRAY_API_KEY
    skip_cleanup: true
    on:
        tags: true
