---
branches:
  only:
    - master
language: java
jdk: openjdk8
before_script:
  - 'git checkout deployment'
  - 'git rebase master'
after_success:
  - './gradlew run --args=docs/index.html'
  - 'head docs/index.html'
  - 'git add docs'
  - 'git commit -m "commit build artifacts"'
  - 'git status'
  - 'git remote add authd https://cmosher01:$GITHUB_TOKEN@github.com/cmosher01/Solarized-Study.git'
  - 'git push authd deployment'
deploy:
    provider: bintray
    file: build/bintray.json
    user: $BINTRAY_USERNAME
    key: $BINTRAY_API_KEY
    skip_cleanup: true
    on:
        tags: true
